version: '3'

services:
  angular-webapp:
    build:
      context: ./angular-ticket-system
    ports:
      - "4200:4200"
    restart: always

  spring-boot-server:
    build:
      context: ./ticket-system/ticket-system
    ports:
      - "8080:8080"
    environment:
      # Add environment variables for Kafka and MongoDB configuration
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=ticket-system
      - spring.data.mongodb.username=admin
      - spring.data.mongodb.password=password
      # App Properties
      - ticket-system.app.jwtCookieName= ticket-system
      - ticket-system.app.jwtSecret= ======================TicketSystem=Spring===========================
      - ticket-system.app.jwtExpirationMs= 86400000
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.kafka.group-id=ticket-system
    depends_on:
      - kafka
      - mongo
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
